/**
 * exportReport.js
 * Browser-native export of LatentTwin scan results.
 * No third-party dependencies. Uses Blob + URL.createObjectURL.
 * Never exports secrets.
 */

function isoDate() {
  return new Date().toISOString().slice(0, 10);
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Clean up after browser has time to start the download
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

/**
 * Build the safe export payload from live React state.
 * analysisSnapshot: { nodes, edges, impacted: Set }
 * repoUrl: string
 */
function buildPayload(analysisSnapshot, repoUrl) {
  const { nodes = [], edges = [], impacted = new Set() } = analysisSnapshot ?? {};

  const impactedNodes = nodes.filter(n => n.status === 'impacted' || n.status === 'affected-downstream');
  const issueCount = nodes.reduce((acc, n) => acc + (n.lines?.filter(l => l.error).length ?? 0), 0);

  return {
    product: 'LatentTwin',
    repository: repoUrl || 'unknown',
    generatedAt: new Date().toISOString(),
    summary: {
      risk: impactedNodes.length > 0 ? (impactedNodes.length > 3 ? 'HIGH' : 'MEDIUM') : 'LOW',
      issues: issueCount,
      affectedFiles: impactedNodes.length,
      affectedServices: [...new Set(impactedNodes.map(n => (n.file || '').split('/')[0]))].filter(Boolean).length,
    },
    diagnosis: nodes
      .filter(n => n.status === 'impacted' || n.status === 'affected-downstream')
      .map(n => ({
        file: n.file,
        label: n.label,
        status: n.status,
        role: n.role ?? null,
        tier: n.tier ?? null,
        issues: (n.lines ?? []).filter(l => l.error).map(l => ({
          lineNumber: l.lineNumber ?? null,
          code: l.code,
          hint: l.hint ?? null,
          before: l.before ?? null,
          after: l.after ?? null,
        })),
      })),
    blastRadius: {
      nodes: [...impacted],
      edges: edges
        .filter(e => impacted.has(e.source) || impacted.has(e.target))
        .map(e => ({ source: e.source, target: e.target, type: e.type ?? null })),
    },
    graph: {
      totalNodes: nodes.length,
      totalEdges: edges.length,
    },
  };
}

/** Export as JSON */
export function exportJSON(analysisSnapshot, repoUrl) {
  const payload = buildPayload(analysisSnapshot, repoUrl);
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
  triggerDownload(blob, `latenttwin-report-${isoDate()}.json`);
}

/** Export as Markdown */
export function exportMarkdown(analysisSnapshot, repoUrl) {
  const p = buildPayload(analysisSnapshot, repoUrl);

  const diagLines = p.diagnosis.flatMap(d => {
    const issueLines = d.issues.map(i =>
      `  - Line ${i.lineNumber ?? '?'}: \`${i.code}\`` +
      (i.hint ? `\n    > ${i.hint}` : '') +
      (i.before && i.after ? `\n    - Before: \`${i.before}\`\n    - After: \`${i.after}\`` : '')
    );
    return [
      `### ${d.file}`,
      `- Status: **${d.status}**${d.tier ? ` | Tier: ${d.tier}` : ''}${d.role ? ` | Role: ${d.role}` : ''}`,
      ...(issueLines.length > 0 ? ['- Issues:', ...issueLines] : ['- No diagnostic lines flagged.']),
      '',
    ];
  });

  const blastList = p.blastRadius.nodes.length > 0
    ? p.blastRadius.nodes.map(n => `- ${n}`)
    : ['- None detected.'];

  const blastEdges = p.blastRadius.edges.length > 0
    ? p.blastRadius.edges.map(e => `- ${e.source} → ${e.target}${e.type ? ` (${e.type})` : ''}`)
    : ['- None.'];

  const md = [
    '# LatentTwin Scan Report',
    '',
    '## Repository',
    `\`${p.repository}\``,
    '',
    `Generated: ${p.generatedAt}`,
    '',
    '---',
    '',
    '## Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Risk | **${p.summary.risk}** |`,
    `| Issues detected | ${p.summary.issues} |`,
    `| Affected files | ${p.summary.affectedFiles} |`,
    `| Affected services | ${p.summary.affectedServices} |`,
    `| Total graph nodes | ${p.graph.totalNodes} |`,
    `| Total graph edges | ${p.graph.totalEdges} |`,
    '',
    '---',
    '',
    '## Diagnosis',
    '',
    ...(diagLines.length > 0 ? diagLines : ['No issues found.']),
    '---',
    '',
    '## Blast Radius',
    '',
    '### Affected Nodes',
    ...blastList,
    '',
    '### Affected Edges',
    ...blastEdges,
    '',
    '---',
    '',
    `*Generated by [LatentTwin](https://github.com/latent-twin) · ${p.generatedAt}*`,
    '',
  ].join('\n');

  const blob = new Blob([md], { type: 'text/markdown' });
  triggerDownload(blob, `latenttwin-report-${isoDate()}.md`);
}
